from __future__ import annotations

# This file contains the list of tickers that we are interested in.
# The tickers are classified into different categories such as
# single stock, single crypto, Dow 30, Nasdaq 100, SP 500(Top 10), and FX.

SINGLE_TICKER = ["AAPL"]
SINGLE_CRYPTO_TICKER = ["BTC-USD"]

# Dow 30 constituents in 2025/03
# https://www.cnbc.com/dow-30/
DOW_30_TICKER = [
    "AMZN",
    "AXP",
    "AMGN",
    "AAPL",
    "BA",
    "CAT",
    "CSCO",
    "CVX",
    "GS",
    "HD",
    "HON",
    "IBM",
    "JNJ",
    "KO",
    "JPM",
    "MCD",
    "MMM",
    "MRK",
    "MSFT",
    "NKE",
    "PG",
    "SHW",
    "TRV",
    "UNH",
    "CRM",
    "NVDA",
    "VZ",
    "V",
    "WMT",
    "DIS",
]

# Nasdaq 100 constituents at 2025/03
# https://indexes.nasdaqomx.com/Index/Weighting/NDX
NAS_100_TICKER = [
    "AAPL",
    "ABNB",
    "ADBE",
    "ADI",
    "ADP",
    "ADSK",
    "AEP",
    "AMAT",
    "AMD",
    "AMGN",
    "AMZN",
    "ANSS",
    "APP",
    "ARM",
    "ASML",
    "AVGO",
    "AXON",
    "AZN",
    "BIIB",
    "BKNG",
    "BKR",
    "CCEP",
    "CDNS",
    "CDW",
    "CEG",
    "CHTR",
    "CMCSA",
    "COST",
    "CPRT",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTSH",
    "DASH",
    "DDOG",
    "DXCM",
    "EA",
    "EXC",
    "FANG",
    "FAST",
    "FTNT",
    "GEHC",
    "GFS",
    "GILD",
    "GOOG",
    "GOOGL",
    "HON",
    "IDXX",
    "INTC",
    "INTU",
    "ISRG",
    "KDP",
    "KHC",
    "KLAC",
    "LIN",
    "LRCX",
    "LULU",
    "MAR",
    "MCHP",
    "MDB",
    "MDLZ",
    "MELI",
    "META",
    "MNST",
    "MRVL",
    "MSFT",
    "MSTR",
    "MU",
    "NFLX",
    "NVDA",
    "NXPI",
    "ODFL",
    "ON",
    "ORLY",
    "PANW",
    "PAYX",
    "PCAR",
    "PDD",
    "PEP",
    "PLTR",
    "PYPL",
    "QCOM",
    "REGN",
    "ROP",
    "ROST",
    "SBUX",
    "SNPS",
    "TEAM",
    "TMUS",
    "TSLA",
    "TTD",
    "TTWO",
    "TXN",
    "VRSK",
    "VRTX",
    "WBD",
    "WDAY",
    "XEL",
    "ZS",
]

# SP 500 constituents at 2025/03
# https://www.spglobal.com/spdji/en/indices/equity/sp-500/#data
SP_500_TOP_10_TICKER = [
    "AAPL",
    "NVDA",
    "MSFT",
    "AMZN",
    "META",
    "GOOGL",
    "BRK.B",
    "AVGO",
    "GOOG",
    "TSLA"
]

# Crypto Ticker
CRYPTO_TICKER = [
    "BTC-USD",
    "ETH-USD",
    "XRP-USD",
    "USDT-USD",
    "SOL-USD",
    "BNB-USD",
    "USDC-USD",
    "DOGE-USD",
    "ADA-USD",
    "TRX-USD",
    "XLM-USD",
    "WBTC-USD"
]

# FX Ticker
FX_TICKER = [
    "AUDCAD=X",
    "AUDCHF=X",
    "AUDJPY=X",
    "AUDNZD=X",
    "AUDSGD=X",
    "AUDUSD=X",
    "AUDUSD=X",
    "AUDUSD=X",
    "AUDUSD=X",
    "AUDUSD=X",
    "AUDUSD=X",
    "AUDUSD=X",
    "CADCHF=X",
    "CADHKD=X",
    "CADJPY=X",
    "CHFJPY=X",
    "CHFSGD=X",
    "EURAUD=X",
    "EURCAD=X",
    "EURCHF=X",
    "EURCHF=X",
    "EURCHF=X",
    "EURCZK=X",
    "EURGBP=X",
    "EURHKD=X",
    "EURHUF=X",
    "EURJPY=X",
    "EURNOK=X",
    "EURNZD=X",
    "EURPLN=X",
    "EURRUB=X",
    "EURSEK=X",
    "EURSGD=X",
    "EURTRY=X",
    "EURTRY=X",
    "EURUSD=X",
    "GBPAUD=X",
    "GBPAUD=X",
    "GBPAUD=X",
    "GBPCAD=X",
    "GBPCHF=X",
    "GBPJPY=X",
    "GBPNZD=X",
    "GBPUSD=X",
    "HKDJPY=X",
    "NZDCAD=X",
    "NZDCHF=X",
    "NZDJPY=X",
    "NZDUSD=X",
    "SGDJPY=X",
    "TRYJPY=X",
    "USDCAD=X",
    "USDCHF=X",
    "USDCNH=X",
    "USDCZK=X",
    "USDHKD=X",
    "USDHUF=X",
    "USDILS=X",
    "USDJPY=X",
    "USDMXN=X",
    "USDNOK=X",
    "USDPLN=X",
    "USDRON=X",
    "USDRUB=X",
    "USDSEK=X",
    "USDSGD=X",
    "USDTHB=X",
    "USDTRY=X",
    "USDZAR=X",
    "XAGUSD=X",
    "XAUUSD=X",
    "ZARJPY=X",
    "EURDKK=X",
]
